fun main (args : Array<String>){
    //The maximum and minimum value for a byte type (8 bit)
    println("Byte type")
    println("Min value: " + Byte.MAX_VALUE)
    println("Max value: " + Byte.MIN_VALUE + "\n")
    //The maximum and minimum value for a short type (16 bit)
    println("Short type")
    println("Min value: " + Short.MAX_VALUE)
    println("Max value: " + Short.MIN_VALUE + "\n")
    //The maximum and minimum values ​​for integers (32 bit)
    println("Int type")
    println("Max value: " + Int.MAX_VALUE)
    println("Min value: " + Int.MIN_VALUE + "\n")
    //The maximum and minimum value for a long type (64 bit)
    println("Long type")
    println("Max value: " + Long.MAX_VALUE)
    println("Min value: " + Long.MIN_VALUE + "\n")
    //The maximum and minimum value for a float type (32 bit)
    println("Float type")
    println("Max value: " + Float.MAX_VALUE)
    println("Min value: " + Float.MIN_VALUE + "\n")
    //The maximum and minimum value for a double type (64 bit)
    println("Double type")
    println("Max value: " + Double.MAX_VALUE)
    println("Min value: " + Double.MIN_VALUE)
}